begin;

create table if not exists public.history_users (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  telegram_username text,
  telegram_first_name text,
  telegram_last_name text,
  first_name text not null,
  last_name text not null,
  is_active boolean not null default true,
  registered_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists history_users_active_registered_idx
  on public.history_users(is_active, registered_at desc);

alter table public.history_bot_state
  drop constraint if exists history_bot_state_state_check;

alter table public.history_bot_state
  add constraint history_bot_state_state_check
  check (state in (
    'idle',
    'awaiting_quiz',
    'preview',
    'choosing_group',
    'choosing_time',
    'awaiting_admin_id',
    'awaiting_first_name',
    'awaiting_last_name'
  ));

alter table public.history_users enable row level security;

comment on table public.history_users is 'Registered ARK Tarix Web App users linked to authoritative Telegram user IDs';

commit;
