begin;

create table if not exists public.history_quizzes (
  id bigint generated by default as identity primary key,
  title text not null,
  topic text,
  created_by bigint not null,
  status text not null default 'draft' check (status in ('draft','ready','archived')),
  question_count integer not null default 0 check (question_count >= 0),
  default_time_limit integer not null default 20 check (default_time_limit between 5 and 600),
  shuffle_questions boolean not null default false,
  shuffle_options boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.history_questions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.history_quizzes(id) on delete cascade,
  position integer not null check (position > 0),
  question_text text not null,
  option_a text not null,
  option_b text not null,
  option_c text not null,
  option_d text not null,
  correct_option text not null check (correct_option in ('A','B','C','D')),
  explanation text,
  time_limit_seconds integer check (time_limit_seconds is null or time_limit_seconds between 5 and 600),
  created_at timestamptz not null default now(),
  unique (quiz_id, position)
);

create table if not exists public.history_groups (
  id bigint generated by default as identity primary key,
  telegram_chat_id bigint not null unique,
  title text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.history_sessions (
  id bigint generated by default as identity primary key,
  quiz_id bigint not null references public.history_quizzes(id) on delete restrict,
  group_id bigint not null references public.history_groups(id) on delete restrict,
  status text not null default 'running' check (status in ('running','finished','cancelled')),
  current_question_index integer not null default 0 check (current_question_index >= 0),
  question_order bigint[] not null default '{}',
  default_time_limit integer not null default 20 check (default_time_limit between 5 and 600),
  current_question_id bigint references public.history_questions(id) on delete set null,
  current_poll_id text,
  current_message_id bigint,
  current_question_opened_at timestamptz,
  current_question_deadline_at timestamptz,
  started_by bigint not null,
  started_at timestamptz not null default now(),
  ended_at timestamptz,
  created_at timestamptz not null default now()
);

create unique index if not exists history_sessions_one_running_per_group_uidx
  on public.history_sessions(group_id)
  where status = 'running';

create index if not exists history_sessions_current_poll_idx
  on public.history_sessions(current_poll_id)
  where current_poll_id is not null;

create table if not exists public.history_players (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.history_sessions(id) on delete cascade,
  telegram_user_id bigint not null,
  username text,
  display_name text not null,
  joined_at timestamptz not null default now(),
  total_score integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  total_response_ms bigint not null default 0,
  unique (session_id, telegram_user_id)
);

create table if not exists public.history_answers (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.history_sessions(id) on delete cascade,
  question_id bigint not null references public.history_questions(id) on delete cascade,
  player_id bigint not null references public.history_players(id) on delete cascade,
  selected_option text not null check (selected_option in ('A','B','C','D')),
  is_correct boolean not null,
  response_time_ms integer not null check (response_time_ms >= 0),
  score_awarded integer not null default 0 check (score_awarded >= 0),
  answered_at timestamptz not null default now(),
  unique (session_id, question_id, player_id)
);

create index if not exists history_answers_session_idx on public.history_answers(session_id);
create index if not exists history_answers_question_idx on public.history_answers(question_id);

create table if not exists public.history_results (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.history_sessions(id) on delete cascade,
  player_id bigint not null references public.history_players(id) on delete cascade,
  rank integer not null check (rank > 0),
  score integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  accuracy_percent numeric(5,2) not null default 0,
  average_response_ms integer not null default 0,
  created_at timestamptz not null default now(),
  unique (session_id, player_id)
);

create table if not exists public.history_bot_state (
  telegram_user_id bigint primary key,
  state text not null default 'idle' check (state in ('idle','awaiting_quiz','preview','choosing_group','choosing_time')),
  payload_json jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.history_quizzes enable row level security;
alter table public.history_questions enable row level security;
alter table public.history_groups enable row level security;
alter table public.history_sessions enable row level security;
alter table public.history_players enable row level security;
alter table public.history_answers enable row level security;
alter table public.history_results enable row level security;
alter table public.history_bot_state enable row level security;

comment on table public.history_quizzes is 'ARK Tarix Quiz Bot reusable quizzes';
comment on table public.history_sessions is 'ARK Tarix Quiz Bot live group quiz sessions';

commit;
