begin;

create table if not exists public.history_admins (
  id bigint generated by default as identity primary key,
  telegram_user_id bigint not null unique,
  display_name text,
  role text not null default 'admin' check (role in ('admin')),
  created_by bigint not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists history_admins_active_idx
  on public.history_admins(is_active, created_at);

create table if not exists public.history_settings (
  id integer primary key default 1 check (id = 1),
  default_time_limit integer not null default 20 check (default_time_limit in (10,15,20,30,45,60)),
  shuffle_questions boolean not null default false,
  shuffle_options boolean not null default false,
  updated_by bigint,
  updated_at timestamptz not null default now()
);

insert into public.history_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.history_bot_state
  drop constraint if exists history_bot_state_state_check;

alter table public.history_bot_state
  add constraint history_bot_state_state_check
  check (state in ('idle','awaiting_quiz','preview','choosing_group','choosing_time','awaiting_admin_id'));

alter table public.history_admins enable row level security;
alter table public.history_settings enable row level security;

comment on table public.history_admins is 'Dynamic Telegram admins for ARK Tarix Quiz Bot';
comment on table public.history_settings is 'Singleton global defaults for ARK Tarix Quiz Bot';

commit;
